<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-K5UJHKQ" failures="1" tests="9" name="com.BHL.TC001_LoginPageTest" time="15.268" errors="0" timestamp="2025-05-20T15:33:46 IST" skipped="0">
  <testcase classname="com.BHL.TC001_LoginPageTest" name="afterSuite" time="0.003">
    <failure message="The following asserts failed:
	The user name does not match did not expect [Chitra Patil] but found [Chitra Patil]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
The user name does not match did not expect [Chitra Patil] but found [Chitra Patil]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.BHL.BeforeAfterMethods.afterSuite(BeforeAfterMethods.java:71)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:565)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:386)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- afterSuite -->
  <testcase classname="com.BHL.TC001_LoginPageTest" name="TC_001_verify_WelcomeText_On_LoginPage" time="0.142"/>
  <testcase classname="com.BHL.TC001_LoginPageTest" name="TC_002_verify_Login_Button_Clickable" time="1.392"/>
  <testcase classname="com.BHL.TC001_LoginPageTest" name="TC003_verify_ErrorMessageForEmailField" time="0.684"/>
  <testcase classname="com.BHL.TC001_LoginPageTest" name="TC004_verify_ErrorMessageForPasswordField" time="0.088"/>
  <testcase classname="com.BHL.TC001_LoginPageTest" name="TC_005_verify_Login" time="5.706"/>
  <testcase classname="com.BHL.TC001_LoginPageTest" name="TC_006_Logout" time="0.070"/>
  <testcase classname="com.BHL.TC001_LoginPageTest" name="TC_007_LogoutFlow" time="3.526"/>
  <testcase classname="com.BHL.TC001_LoginPageTest" name="TC_008_reloginToBHL" time="3.657"/>
</testsuite> <!-- com.BHL.TC001_LoginPageTest -->
